#include "CreateProject.h"

namespace fs = std::filesystem;

std::string name, infomessage, yesno;

//checks if the path exists.
bool Path_works(const std::string pathstring)
{
	fs::path check(pathstring);
	return fs::exists(check);

}

int dir(std::string path)
{
	std::ifstream file;

	//ask what should we name the proj
	std::cout << "What would you like to call this project? ";
	//take the input, in the same line.
	std::getline(std::cin >> std::ws, name);std::cout << std::endl;

	std::cout << "Attempting to Create project at: " + path << std::endl;


	if(!Path_works(path)) //if the path exists
	{ 
		std::cout << "--ERROR-- Path " + path + " does not exist. " << std::endl; return -1; 
	}

	file.open(path + "\\" + name + "\\proj");
	if (file) //if a project is there already
	{
		std::cout << "--ERROR-- There is a project at " + path + " that exist. " << std::endl; return -1;
	}


	//we passed the check, keep going.
	std::cout << "Creating Project " + name + " at " + path << std::endl;


	//now we are going to need to create the project, with the version files, and to make sure its not a already written dir. But thats really it.


	//create the file
	_mkdir((path + "\\" + name).c_str());


	//now we create the file that stores its name and last date updated. Might add more later
	std::ofstream pathfile((path + "\\" + name) + "\\proj");
	time_t timestamp;

	
	//now we open that new proj file
	if (pathfile.is_open())
	{
		//write name time to it
		pathfile << name << std::endl;

		pathfile << time(&timestamp) << std::endl;

		pathfile.close();
	}

	std::cout << "Created main file" << std::endl;


	std::cout << "project created." << std::endl;

	//Create the gitignore.
	//this will block some files, and we can maybe find similar things from github.


	//-- This is how it should be structured -- (imported from a example file)

	/*
		# Comments start with # 
		

		# Ignore specific files
		/ file1.txt             # Ignores file1.txt in the root directory only
		#file[3 - 5].txt         # Ignores files like file3.txt, file4.txt, file5.txt - this will be the hardest to code.

		# Ignore files by extension at any level
		* .log                  # Ignores all files ending with.log in any directory
		* .tmp                  # Ignores all files ending with.tmp

		# Ignore an entire directory(must end with a slash / )
		build / # Ignores the 'build' directory and everything inside it
		/ node_modules / 
		.venv / 
		.vscode / 

		# Ignore files generated by the OS or IDEs
		.DS_Store              # macOS specific files
		Thumbs.db              # Windows specific files

		# Environment variables and sensitive data
		.env                   # Ignore files containing sensitive credentials

		# Negation: Re - include a specific file inside an ignored directory
		!important.log         # Re - includes important.log, even if the file exention .log is ignored
*/


	//we should loop through each line in a file, check the file extension, like ., /, !, *.
	//then what we need to do, is to skip em files when we commit.
	
	bool loop = true;

	while (loop)
	{

		std::string answer;

	std::cout << "Create a git ignore file? Y/N";
		std::getline(std::cin >> std::ws, answer); std::cout << std::endl;

		if (answer == "N" || answer == "n")
		{
			std::cout << "Project complete" << std::endl;
			return 0;
		}
		if (answer == "Y" || answer == "y")
		{
			loop = false;
		}
	}


	//create the file
	

	std::ofstream gitignore((path + "\\" + name) + "\\ .gitignore");
	//now we open that new proj file
	if (gitignore.is_open())
	{
		
		//preheat with some data.


	gitignore << "# The way this git ignore file works is the same as GitHub, all functions work on it. \n \n";
		gitignore << "OS junk\n" ;
		gitignore << ".DS_Store\n";
		gitignore << "Thumbs.db\n \n";

		gitignore << "# Build outputs\n";
		gitignore << "build / \n";
		gitignore << "dist / \n \n";

		gitignore << "# IDE\n";
		gitignore << ".vscode / \n";
		gitignore << ".idea / \n";



		gitignore.close();
	}
	else
	{
		//ERROR COLOR PRINT - USES ANSI codes
		//prints like printf(" Start [color] {text} End [normal color] /break
		printf("\033[31mERROR - DIR/FILE MAY NOT EXIST - 404\033[0m\n");
		//std::cout << "" << std::endl;
		return -1;
	}










	std::cout << "Project complete." << std::endl;
	//std::cout << "Test" << std::endl;



	//end

	return 0;

	
	}


	
